describe('Test Senarios', ()=>{

    it('Verify user Sign up succefully',()=>{
        cy.visit('https://automationexercise.com/')
        cy.get('.shop-menu > .nav > :nth-child(4)').should('be.exist').click()
        cy.get('[data-qa="signup-name"]').should('be.visible').type('Olatunji@1010')
        cy.get('[data-qa="signup-email"]').should('be.visible').type('organdonor910@gmail.com')
        cy.get('[data-qa="signup-button"]').should('be.exist').click()
        cy.get('[id="id_gender1"]').should('not.be.disabled').click()
        cy.get('[data-qa="password"]').should('be.empty').and('be.enabled').type('Olatunji@1010')
        cy.get('[data-qa="days"]').select('20').should('have.value', '20')
        cy.get('[data-qa="months"]').should('be.visible').and('be.enabled').select('May')
        cy.get('[data-qa="years"]').and('be.enabled').select('2002').find('option:selected').should('have.text', '2002')
        cy.get('[id="newsletter"]').should('be.exist').click()
        cy.get('[id="optin"]').should('be.exist').click().should('be.checked')
        cy.get('[data-qa="first_name"]').and('be.empty','be.visible').type('Olatunji')
        cy.get('[data-qa="last_name"]').and('be.empty','be.visible').type('Nicholas')
        cy.get('[data-qa="company"]').and('exist').type('LG accesseroies')
        cy.get('[data-qa="address"]').and('exist','visible').type('12 salako')
        cy.get('[data-qa="address2"]').should('be.empty','visible').type('Ketu')
        cy.get('[data-qa="country"]').should('be.exist').select('Canada')
        cy.get('[data-qa="state"]').and('be.exist','be.empty').type('Lagos')
        cy.get('[data-qa="city"]').should('be.exist','.visible').type('Ketu')  
        cy.get('[data-qa="zipcode"]').should('be.visible').and('be.empty').type('AS12324')
        cy.get('[data-qa="mobile_number"]').should('be.visible').type('07032453564').should('have.value', '07032453564')
        cy.get('[data-qa="create-account"]').should('exist').and('be.visible').click()
        cy.get('[data-qa="continue-button"]').should('exist').and('be.visible').click()
        cy.get('[href="/logout"]').should('exist').and('be.visible').click()
    })

    it('Verify user can Login successfully',()=>{
        cy.visit('https://automationexercise.com/')
        cy.get('[href="/login"]').should('be.exist','visible').click()
        cy.get('[data-qa="login-email"]').should('be.exist','visible').and('be.empty').type('organdonor910@gmail.com')
        cy.get('[data-qa="login-password"]').should('be.exist','visible').and('be.empty').type('Olatunji@1010')
        cy.get('[data-qa="login-button"]').should('be.exist').click()
        cy.get('[href="/logout"]').should('be.visible').click()
        })

    it('Verify user can Add to cart', ()=> {
        cy.visit('https://automationexercise.com/')
        cy.get('[href="/login"]').should('exist').click()
        cy.get('[data-qa="login-email"]').should('be.exist','empty','visible').type('organdonor910@gmail.com')
        cy.get('[data-qa="login-password"]').should('be.exist','empty','visible').type('Olatunji@1010')
        cy.get('[data-qa="login-button"]').should('exist').click()
        cy.get('[href="/products"]').should('be.visible').click()
        cy.get('img[src="/get_product_picture/2"]').should('be.exist').click()
        cy.get(':nth-child(3) > .product-image-wrapper > .single-products > .productinfo').should('be.exist').click()
        cy.get(':nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn').should('exist').click()
        cy.get('.modal-footer > .btn').should('be.exist').click()
        cy.get(':nth-child(4) > .product-image-wrapper > .single-products > .productinfo').should('exist').click()
        cy.get(':nth-child(4) > .product-image-wrapper > .single-products > .productinfo > .btn').should('be.visible').click()
        cy.get('.modal-footer > .btn').should('be.exist').click()
        cy.get(':nth-child(5) > .product-image-wrapper > .single-products > .productinfo').should('be.exist').click()
        cy.get(':nth-child(5) > .product-image-wrapper > .single-products > .productinfo > .btn').should('be.visible').click()
        cy.get('.modal-footer > .btn').should('be.visible').click()
        cy.get(':nth-child(6) > .product-image-wrapper > .single-products > .productinfo').should('be.visible').click()
        cy.get(':nth-child(6) > .product-image-wrapper > .single-products > .productinfo > .btn').should('be.exist').click()
        cy.get('.modal-footer > .btn').should('exist').click()
        cy.get(':nth-child(7) > .product-image-wrapper > .single-products > .productinfo').should('be.visible').click()
        cy.get(':nth-child(7) > .product-image-wrapper > .single-products > .productinfo > .btn').should('exist').click()
        cy.get('.modal-footer > .btn').should('be.visible').click()
        cy.get('.shop-menu > .nav > :nth-child(3) > a').should('be.exist').click()
        
    })
 })  