describe('LOGIN', () => {
  it('Verify user login invalid credential', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.get('[name="user-name"]').type('123242535')
    cy.get('[name="password"]').type('luckky')
    cy.get('[name="login-button"]').click()
    
  })
    it('verify user login with valid credential',()=> {
      cy.visit('https://www.saucedemo.com/')
      cy.get('[data-test="username"]').type('standard_user')
      cy.get('[data-test="password"]').type('secret_sauce')
      cy.get('[data-test="login-button"]').click()
      cy.get('[data-test="product-sort-container"]').select("az")
      cy.get('[data-test="product-sort-container"]').select("lohi")
      cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
      cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
      cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click()
      cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
      cy.get('[data-test="remove-sauce-labs-fleece-jacket"]').click()
      cy.get('[data-test="remove-sauce-labs-bolt-t-shirt"]').click()
      cy.get('[data-test="shopping-cart-link"]').click()
      cy.get('[data-test="checkout"]').click()
      cy.get('[data-test="firstName"]').type("Olatunji")
      cy.get('[data-test="lastName"]').type('Nicholas')
      cy.get('[data-test="postalCode"]').type('23435')
      cy.get('[data-test="continue"]').click()
      cy.get('[data-test="finish"]').click()
      cy.get('[data-test="back-to-products"]').click()
    })
  
})